sample_driver: fix issue #116 : handle of LIST command
fclairamb/ftpserverlib pull request #123
Opened 2020-03-17 19:57 UTC by zavla

2020-03-25 01:22 UTC, fclairamb requested changes

2020-03-25 01:22 UTC, fclairamb commented on prepare.bat
> +go get -t -v
Please remove this file

2020-03-25 01:22 UTC, fclairamb commented on server/handle_dirs.go
> +func qoutedoubling(s string) string {
Please rename it `quoteDoubling`

2020-03-25 01:22 UTC, fclairamb commented on tests/handle_dirs_test.go
> +				expectedfileName = " with spaces"
Is it not possible to have a space at the end of a file in windows ?

2020-03-25 01:24 UTC, fclairamb commented
These changes seem reasonable for the most part. What is blocking the build is that you are using `strings.ReplaceAll` which is a go 1.12+ API. But that's OK, I don't have a real reason for keeping the last 3 versions of go, the last 2 is enough.

2020-03-25 18:19 UTC, zavla commented on tests/handle_dirs_test.go
> +				expectedfileName = " with spaces"
Hello. No, such files are inaccessible.
https://docs.microsoft.com/en-gb/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#naming_conventions

> Do not end a file or directory name with a space or a period. Although the underlying file system may support such names, the Windows shell and user interface does not.

2020-03-29 19:11 UTC, fclairamb commented on server/handle_dirs.go
> +func qoutedoubling(s string) string {
@zavla you still haven't fixed that

2020-03-29 19:15 UTC, fclairamb commented
@zavla there's still written `qouteDoubling` instead of `quoteDoubling` everywhere.

2020-03-30 23:05 UTC, fclairamb approved these changes
LGTM

2020-03-31 00:27 UTC, merged