Allow passing in an existing net.Listener and a public ip resolver.
fclairamb/ftpserverlib pull request #53
Opened 2017-12-26 22:27 UTC by marshallbrekka

This allows the user to provide the mechanisms to get the PASV command to work when running behind a load balancer that supports the proxy protocol by supplying a proxy protocol enabled net.Listener, and a PublicIpResolver that takes the ClientContext and returns the public ip to return to the client.

2017-12-27 13:41 UTC, fclairamb commented
Very good idea. Can you execute `./prepare.sh` and fix the issues ?

2017-12-27 13:43 UTC, fclairamb requested changes
Very good idea, please execute `./prepare.sh` to fix the issues that travis is reporting.

2017-12-27 13:43 UTC, fclairamb commented on server/driver.go
> +	LocalAddr() net.Addr
Shouldn't we rename it to `ListenAddr` to make it a bit more explicit ?

2017-12-27 13:43 UTC, fclairamb commented on server/driver.go
> +type PublicIpResolver func(ClientContext) (string, error)
Missing comment

2017-12-27 18:18 UTC, marshallbrekka commented on server/driver.go
> +	LocalAddr() net.Addr
Im open to a name change, but figured it would make more sense to expose it under the same name as the connection object it is coming from.
Its also not guaranteed that the address is actually the same as the listener address (again from my use case, it will be the private IP of the load balancer that is forwarding the request).


I had originally written this (when prototyping for my own uses) to pass the net.Conn object to the PublicIPResolver, but figured that exposed too much, and instead opted to abstract it behind the ClientContext.

2017-12-27 19:09 UTC, marshallbrekka commented
@fclairamb fixed linter issues

2017-12-27 22:45 UTC, fclairamb approved these changes

2017-12-28 00:11 UTC, marshallbrekka commented
Great, feel free to merge (i can't)

2017-12-28 06:59 UTC, mgenov approved these changes
LGTM !

2017-12-28 11:09 UTC, merged